---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageDigestMirrorSet
metadata:
  name: example-mirror-set
spec:
  imageDigestMirrors:
    - mirrors:
        - quay.io/yashn/konflux-test-yashnn
      source: quay.io/redhat-user-workloads/konflux-samples-tenant/olm-operator/gatekeeper
    - mirrors:
        - quay.io/redhat-user-workloads/konflux-sec-eng-spec-tenant/nbde-tang-server-multiarch-bundle
      source: registry.redhat.io/nbde-tang-server/nbde-tang-server-operator-bundle
