---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageDigestMirrorSet
metadata:
  name: example-mirror-set
spec:
  imageDigestMirrors:
    - mirrors:
        - quay.io/yashn/konflux-test-yashn
        - quay.io/something-else
      source: quay.io/redhat-user-workloads/konflux-samples-tenant/olm-operator/gatekeeper
